# Generated by Django 3.1.7 on 2021-04-03 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webchat', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='cnannel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_cnannel', to='webchat.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
