# Generated by Django 3.1.7 on 2021-04-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0006_auto_20210403_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='cnannel_id',
            new_name='cnannel',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
